### PR TITLE
Putting F.Fab REF** inside the component box for C_0603 thru C_2225

### PR DESCRIPTION
**Pull request by jensenr30**
I only put F.Fab REF** inside the boxes on the footprints where it seemed reasonable to do so.
I think it looks pretty good now.

### CODE REVIEW

**Comment by poeschlr** [comment]
I think you can increase the font size for all footprints larger than 0805 (If the text REF** has enough space, most references should also find space.)

**Comment by SchrodingersGat** [comment]
Agreed, if text fits at `1, 1, 0.15` then it should be set to that, and only decreased in size if absolutely required.

**Comment by poeschlr** [comment]
@jensenr30 could you fix the font sizes such that we can merge this?

**Comment by jensenr30** [comment]
@poeschlr @SchrodingersGat 
Sorry! I don't know what is wrong with the font sizes so I don't know how to fix them.

**Comment by poeschlr** [comment]
You choose a very small font size for the second reference in all the footprints this pull request does touch. It would be way better if you look at each footprint and determine the maximum size possible. (with an upper limit of 1,1,0.15)

**Comment by poeschlr** [comment]
In the new repo the capacitors have their reference inside. (They are script generated.)
See pull request: https://github.com/KiCad/kicad-footprints/pull/3

This repo is now declared legacy. No further pull requests will be accepted.

**Pull request closed without merging**
