### PR TITLE
Create GRM15.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
footprint according to Muratas own recommendation for their GRM15 series 0402 capacitors.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

first of all: thanks for the contriution. 
Second: There are some KLC-issues with your component:
```
checking module: GRM15
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```
1. Could you fix them? You can check KLC-conformity also with our set of python scripts: https://github.com/KiCad/kicad-library-utils
2. Also it would be good, if your footprint's name would start with a `C_` (as all the others in this lib).
3. Could you add some silkscreen (e.g. two horizontal lines) to indicate the the two pins belong to one part, e.g. 
grm


Best,
JAN

**Comment by savenlid** [comment]
Hi

You don't silkscreen 0402 components.

I am sorry but you just don't.

If people did your iPhone would be the size of a laptop.

Rest of the comments I will look into.

Regards
Nicholas

Den 24 okt. 2016 21:02 skrev "Jan W. Krieger" <notifications@github.com>:

**Comment by evanshultz** [comment]
@savenlid Will you be able to finish this PR soon?

@jkriege2 Do you have any opinion on the silkscreen? Would this contribution be accepted without any silk?

**Comment by poeschlr** [comment]
@savenlid 
about silk screen:
The new footprints < 0402 don't have silk screen. (unless they need a polarity marker. Then they have a small circle to the left.)
More details: https://github.com/KiCad/kicad-footprints/pull/3

If you are still interested in contributing please reopen this over on the new repo. https://github.com/KiCad/kicad-footprints
(This repo is declared legacy. We do no longer accept pull requests here.)

**Pull request closed without merging**
