### PR TITLE
fixed KLC issues + reduced number of 3D models

### PR DESCRIPTION
**Pull request by jkriege2**
- fixed KLC issues (REFDES on F.Fab, standardized courtyard) 
- HandSoldering uses same 3D mdoel as normal footprint 
- added noSilkscreen-footpritns for very small components

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Jan,  I would suggest suffix with `_NoSilk` rather than `_noSilkscreen` - I think it looks cleaner? Otherwise looks great :)

**Comment by jkriege2** [comment]
Done!

**Comment by SchrodingersGat** [comment]
Sorry to be pedantic - the filenames are `_noSilk` rather than `_NoSilk` - please capitalize the'N' :)

**Comment by jkriege2** [comment]
OK

Am 20.02.2017 um 11:15 schrieb Oliver:

**Comment by SchrodingersGat** [comment]
Thanks Jan :)

**Pull request merged**
