### PR TITLE
Added electrolytic cap 8x5.4mm

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Please, apply the [KLC](https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt) to your footprint. You can check some KLC rules using the [check_kicad_mod](https://github.com/KiCad/kicad-library-utils/tree/master/pcb) script.

**Comment by crackerizer** [comment]
Thank you for the guideline, the footprint now passed the check script.

**Comment by CarlPoirier** [comment]
Hi,

The  c_elec_4x4.5.kicad_mod seems to have some extra courtyard clearance on the left side. Nothing major, though!

**Comment by crackerizer** [comment]
Fixed that and added courtyard to all SMD cap.

**Comment by michal777** [comment]
I can see that the check_kicad_mod produces non standard indentation. Should it be allowed in libraries? @ricardocrudo Is it going to be fixed?

**Comment by crackerizer** [comment]
I didn't run the script with these footprints. It seems the script has some problem and corrupt SMD file. I already reported it to @ricardocrudo .

**Comment by CarlPoirier** [comment]
You have some values and references overlapping with the silkscreen in many cases. Also, there still seems to be subtle differences in the footprint between the 6.3mm and 8mm wide variations. Besides that, it's very nice! The whole library will be compliant now.

**Comment by ricardocrudo** [comment]
@michal777 I don't think it's a problem, it should be compatible. The drawback is that the diff shows all lines changed. The files are saved by the script using a predictable and generic way, KiCad in the other hand uses a non generic way to format the data. Anyway, a workaround for this (for while) is open the file in the Kicad and save it again before submit the pull request.

**Comment by michal777** [comment]
I think that only standard indentation should be allowed in official libraries. This library format was designed to be easy to read by human and introducing different standards doesn't help to learn reading the files. This generic s-expressions format is quite long and reading requires a lot of scrolling. The second problem is that it's more difficult to make changes in the files (like changing line width of silkscreen) with simple methods like using find and replace in text editor. Finally the using the diff doesn't help with tracking changes.

That's why I think pushing all footprints changed by the scripts through the kicad should be obligatory.

**Comment by ricardocrudo** [comment]
I agree, keep files generated by the same parser/builder (KiCad one) is a wise thing to do. Anyway I did small change in the s-expr generator that makes the resultant file more compact, still different in relation to KiCad generated files, although more friendly to read.

Thus, please @crackerizer, make sure that you re-save all files using KiCad before pull request them.

**Comment by crackerizer** [comment]
I have already saved all the footprint using kicad since I found the bug. I think it's safe to merge.

**Comment by michal777** [comment]
At the moment c_elec_8x5.4.kicad_mod is bad.

**Comment by crackerizer** [comment]
c_elec_8x5.4.kicad_mod is fine for me.
screenshot from 2015-06-09 13 52 54

**Comment by michal777** [comment]
I mean it's not saved with kicad:
```
(module c_elec_8x5.4
  (layer F.Cu)
  (tedit 556D18A9)
  (descr "SMT capacitor, aluminium electrolytic, 8x6.5")
...

**Comment by crackerizer** [comment]
Done.

**Comment by ricardocrudo** [comment]
Thanks for adding courtyard line to all capacitors. I'm merging your PR because it makes footprints better then before (regarding KLC), but all footprints still needing to be redrawn because silkscreen is superposing the pads.

**Pull request merged**
