### PR TITLE
addin cp_1311

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
isn't that the same as case B here: https://github.com/KiCad/Capacitors_Tantalum_SMD.pretty ?

**Comment by jeromebeguin** [comment]
I have no idea, I'll check.

**Comment by jeromebeguin** [comment]
The 2 cases are very similar. I'll remove this part.

**Comment by SchrodingersGat** [comment]
Ok to close this PR?

**Comment by jeromebeguin** [comment]
yes sur.

**Pull request closed without merging**
